### ISSUE TITLE
Added 'mango.post' helper function documentation 

### ISSUE THREAD

**Issue by h45h74x** [hkalexling/mango-plugins#1]
Hi,

I am opening this issue to use it as a "pull request" for my changes to this repository's wiki. The changes can be found in this [pull request](https://github.com/hkalexling/Mango/pull/139).

As I am currently working on some new plugins for the manga downloader, I was in dire need of an helper method able to send POST requests in order to communicate with some APIs. I thought my changes could be useful to others as well.

My changes are simply documenting the usage of the new function.

Thank you
 :D

_Because contributing to wikis is kind of weird, here is what you can do to merge my changes according to [this guide](https://gist.github.com/omaraboumrad/35654da0a376c57a2e0ab4d92ad0c339):_

> As a core contributor you can review the changes done using:
> 
> ```
> git checkout -b FOO-master
> git pull https://github.com/FOO/PROJECT.wiki.git master
> ```
> 
> Merging Changes
> 
> As a core contributors you can merge the changes done using:
> 
> ```
> git checkout master
> git merge --no-ff FOO-master
> git push origin master
> ```
>

**Comment by hkalexling** [comment]
Sounds great! I am inviting you to both repositories so you can easily edit the wiki :)

**Comment by h45h74x** [comment]
Thank you!
I've added the new function and its documentation to the wiki.
