### ISSUE TITLE
Issue with Manganelo/manganato

### ISSUE THREAD

**Issue by zeldatp151** [hkalexling/mango-plugins#16]
When I try to get a manga via manganato, it gives me the following error "Search failed. Error: TypeError: cannot read property 'link_story' of undefined"

**Comment by hkalexling** [comment]
What search term did you use? I don't use this Manganelo personally, but when I access https://readmanganato.com/ it says "This site is closed". This might be the reason.

**Comment by zeldatp151** [comment]
so you are correct. https://readmanganato.com does go to a page that says it is closed, and redirs to https://manganato.com. but if you actually open a manga on there to read, it takes you back to the https://readmanganato.com domain to display the manga, for example https://readmanganato.com/manga-be978739/ works but https://manganato.com/manga-be978739/ does not. and the plugin accepts neither.

**Comment by zeldatp151** [comment]
ahh, I think I have found what the problem is, with other plugins, I paste the URL of the manga I want into the search, but with the Manganelo plugin, I have to search just using the NAME of the manga, this should probably be specified somewhere, and if it is, I didn't see it,  I only figured this out after reading through the .js file to try and figure out what was going on.

**Comment by hkalexling** [comment]
Haha usually you can tell from the placeholder. The placeholder on the search box says "Search Manganelo" which indicates that it accepts a search term. For the ehentai plugin, for example, the placeholder is "E-Hentai Gallery URL", so it's quite clear I think. But feel free to submit a PR to improve these.
