### ISSUE TITLE
[Bug] Cannot use MangaDex Plugin

### ISSUE THREAD

**Issue by WarpWing** [hkalexling/mango-plugins#17]
Hello all!

Just want to report that the default MangaDex plugin won't work.
![image](https://user-images.githubusercontent.com/28925758/147191443-84bf9fb7-9e44-4a57-b6ed-defc990ecea2.png)
I'm pretty sure that it's because the API has changed? I don't know enough JS to fix it(kinda, still debugging it but I'm getting nowhere) but if someone can help me find the actual endpoint for it would be dope, I've been searching their docs and haven't gotten a clue

Manga ID: b49fd121-19bf-4344-a8e1-d1be7ca04e08(https://mangadex.org/title/b49fd121-19bf-4344-a8e1-d1be7ca04e08)
Query: https://mangadex.org/api/manga/b49fd121-19bf-4344-a8e1-d1be7ca04e08

**Comment by hkalexling** [comment]
Hi there, yes it's a known issue. See #10. You can subscribe to that thread to get updated.

**Comment by WarpWing** [comment]
> Hi there, yes it's a known issue. See #10. You can subscribe to that thread to get updated.

Thanks! Sorry, I should've looked through previous issues. My bad

**Comment by hkalexling** [comment]
No worries :D
