### ISSUE TITLE
No Plugins Found[Bug]

### ISSUE THREAD

**Issue by mxdios** [hkalexling/mango-plugins#35]
**Describe the bug**
No Plugins Found
We could't find any plugins in the directory /root/mango/plugins

 I downloaded the plug-in and copied it to /root/mango/plugins, but it did not load

**Expected behavior**
Subscription Manager displays a plug-in selection entry，but it does not

**Mango version**
DockerHub  hkalexling/mango:latest

**Comment by hkalexling** [comment]
Did you manage to get it working?

**Comment by mxdios** [comment]
Yes, I have found the cause of the problem. I have put the plug-in into plugins of the host machine, which should be put under docker.  Thank you for reply  @hkalexling
